Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from textblob import TextBlob

Load the dataset

In [2]:
df = pd.read_csv('netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Understand the Dataset

In [3]:
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

Taking the count of ratings available

In [4]:
x= df.groupby(['rating']).size().reset_index(name='counts')
print(x)

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

Creating the Piechart based on Content rating

In [5]:
pieChart = px.pie(x, values='counts', names='rating', title='Distribution of content ratings on Netflix')
pieChart.show()

Analyzing the top 5 Directors on Netflix

In [6]:
df['director'] = df['director'].fillna('Director No Specified')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Director No Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Director No Specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Director No Specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
directors_list =pd.DataFrame()
print(directors_list)

Empty DataFrame
Columns: []
Index: []

In [8]:
directors_list = df['director'].str.split(',', expand=True).stack()
print(directors_list)

0     0          Kirsten Johnson
1     0    Director No Specified
2     0          Julien Leclercq
3     0    Director No Specified
4     0    Director No Specified
                   ...
8802  0            David Fincher
8803  0    Director No Specified
8804  0          Ruben Fleischer
8805  0             Peter Hewitt
8806  0              Mozez Singh
Length: 9612, dtype: object

In [9]:
directors_list = directors_list.to_frame()
print(directors_list)

                            0
0    0        Kirsten Johnson
1    0  Director No Specified
2    0        Julien Leclercq
3    0  Director No Specified
4    0  Director No Specified
...                       ...
8802 0          David Fincher
8803 0  Director No Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [10]:
directors_list.columns = ['Director']
print(directors_list)

                     Director
0    0        Kirsten Johnson
1    0  Director No Specified
2    0        Julien Leclercq
3    0  Director No Specified
4    0  Director No Specified
...                       ...
8802 0          David Fincher
8803 0  Director No Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [11]:
directors = directors_list.groupby(['Director']).size().reset_index(name='Total Counts')
print(directors)

                       Director  Total Counts
0                Aaron Moorhead             2
1                   Aaron Woolf             1
2      Abbas Alibhai Burmawalla             1
3              Abdullah Al Noor             1
4           Abhinav Shiv Tiwari             1
...                         ...           ...
5116                Çagan Irmak             1
5117           Ísold Uggadóttir             1
5118        Óskar Thór Axelsson             1
5119           Ömer Faruk Sorak             2
5120               Şenol Sönmez             2

[5121 rows x 2 columns]

In [12]:
directors = directors[directors.Director != 'Director No Specified']

In [13]:
directors = directors.sort_values(by=['Total Counts'],ascending= False)
print(directors)

                 Director  Total Counts
4021        Rajiv Chilaka            22
4068          Raúl Campos            18
261             Jan Suter            18
3236         Marcus Raboy            16
4652          Suhas Kadav            16
...                   ...           ...
2331  Ivan Andrew Payawal             1
610    Songyos Sugmakanan             1
611          Sonia Dauger             1
612        Sophie Sartain             1
2336           Ivona Juka             1

[5120 rows x 2 columns]

In [14]:
top5Directors = directors.head()
print(top5Directors)

           Director  Total Counts
4021  Rajiv Chilaka            22
4068    Raúl Campos            18
261       Jan Suter            18
3236   Marcus Raboy            16
4652    Suhas Kadav            16

In [ ]:
top5Directors = top5Directors.sort_values(by=['Total Counts'])
barChart =px.bar(top5Directors, x='Total Counts', y='Director', title='Top 5 Directors on Netflix')
barChart.show()

Analyze top 5 actors on the Netflix

In [16]:
df['cast'] = df['cast'].fillna('No Cast Specified')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No Cast Specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Director No Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Director No Specified,No Cast Specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Director No Specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [17]:
cast_df= pd.DataFrame()
print(cast_df)

Empty DataFrame
Columns: []
Index: []

In [18]:
cast_df = df['cast'].str.split(',', expand=True).stack()
print(cast_df)

0     0         No Cast Specified
1     0                Ama Qamata
      1               Khosi Ngema
      2             Gail Mabalane
      3            Thabang Molaba
                    ...
8806  3          Manish Chaudhary
      4              Meghna Malik
      5             Malkeet Rauni
      6            Anita Shabdish
      7     Chittaranjan Tripathy
Length: 64951, dtype: object

In [19]:
cast_df = cast_df.to_frame()
print(cast_df)

                             0
0    0       No Cast Specified
1    0              Ama Qamata
     1             Khosi Ngema
     2           Gail Mabalane
     3          Thabang Molaba
...                        ...
8806 3        Manish Chaudhary
     4            Meghna Malik
     5           Malkeet Rauni
     6          Anita Shabdish
     7   Chittaranjan Tripathy

[64951 rows x 1 columns]

In [20]:
cast_df.columns = ['Actor']
print(cast_df)

                         Actor
0    0       No Cast Specified
1    0              Ama Qamata
     1             Khosi Ngema
     2           Gail Mabalane
     3          Thabang Molaba
...                        ...
8806 3        Manish Chaudhary
     4            Meghna Malik
     5           Malkeet Rauni
     6          Anita Shabdish
     7   Chittaranjan Tripathy

[64951 rows x 1 columns]

In [21]:
actors = cast_df.groupby(['Actor']).size().reset_index(name='Total Counts')
print(actors)

                        Actor  Total Counts
0                         Jr.             2
1       "Riley" Lakdhar Dridi             1
2                'Najite Dede             1
3                    2 Chainz             1
4                        2Mex             1
...                       ...           ...
39292         İbrahim Büyükak             1
39293        İbrahim Çelikkol             1
39294             Şahin Irmak             1
39295          Şükrü Özyıldız             1
39296            Ṣọpẹ́ Dìrísù             1

[39297 rows x 2 columns]

In [22]:
actors = actors[actors.Actor != 'No Cast Specified']
print(actors)

                        Actor  Total Counts
0                         Jr.             2
1       "Riley" Lakdhar Dridi             1
2                'Najite Dede             1
3                    2 Chainz             1
4                        2Mex             1
...                       ...           ...
39292         İbrahim Büyükak             1
39293        İbrahim Çelikkol             1
39294             Şahin Irmak             1
39295          Şükrü Özyıldız             1
39296            Ṣọpẹ́ Dìrísù             1

[39296 rows x 2 columns]

In [23]:
actors = actors.sort_values(by=['Total Counts'],ascending= False)
print(actors)

                      Actor  Total Counts
2612            Anupam Kher            39
26941          Rupa Bhimani            31
30303      Takahiro Sakurai            30
15541         Julie Tejwani            28
23624               Om Puri            27
...                     ...           ...
15288        Joziah Lagonoy             1
15287           Jozef Gjura             1
15286   Joyraj Bhattacharya             1
15285                Joyraj             1
15300            Ju Xiaowen             1

[39296 rows x 2 columns]

In [24]:
top5Actors = actors.head()
print(top5Actors)

                   Actor  Total Counts
2612         Anupam Kher            39
26941       Rupa Bhimani            31
30303   Takahiro Sakurai            30
15541      Julie Tejwani            28
23624            Om Puri            27

In [25]:
top5Actors =top5Actors.sort_values(by=['Total Counts'])
barChart2 =px.bar(top5Actors, x='Total Counts', y='Actor', title='Top 5 Actors on Netflix')
barChart2.show()

Analyzing the content produced on Netflix based on years

In [32]:
df1 = df[['type', 'release_year']]
df1 = df1.rename(columns={'release_year': 'Release Year', 'type': 'Type'})
df2 = df1.groupby(['Release Year', 'Type']).size().reset_index(name='Total Count')

In [33]:
print(df2)

     Release Year     Type  Total Count
0            1925  TV Show            1
1            1942    Movie            2
2            1943    Movie            3
3            1944    Movie            3
4            1945    Movie            3
..            ...      ...          ...
114          2019  TV Show          397
115          2020    Movie          517
116          2020  TV Show          436
117          2021    Movie          277
118          2021  TV Show          315

[119 rows x 3 columns]

In [37]:
df2 = df2[df2['Release Year']>=2000]
graph = px.line(df2, x='Release Year', y='Total Count', color='Type', title='Trend of content produced on Netflix')
graph.show()

Sentiment Analysis of Netflix Content

In [38]:
df3 = df[['release_year', 'description']]
df3 = df3.rename(columns={'release_year': 'Release Year', 'description': 'Description'})
for index, row in df3.iterrows():
  d=row['Description']
  testimonial = TextBlob(d)
  p = testimonial.sentiment.polarity
  if p==0:
    sent = 'Neutral'
  elif p>0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df3.loc[[index,2], 'sentiment']=sent

df3 = df3.groupby(['Release Year', 'sentiment']).size().reset_index(name='Total Count')

df3 = df3[df3['Release Year']>=2005]
barGraph = px.bar(df3, x='Release Year', y='Total Count', color='sentiment', title='Sentiment Analysis of Netflix Content')
barGraph.show()